live_config_reload = true

import = [
  "~/.config/alacritty/themes/toggle-theme.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

# [font.bold]
# style = "Bold"

# [font.bold_italic]
# style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"
# family = "SFMono Nerd Font"
# family = "LigaOperatorMonoNerdFontCompleteMono Nerd Font"
# family = "OverpassM Nerd Font"
# family = "DankMono Nerd Font"
# family = "CaskaydiaCove Nerd Font"
family = "MonoLisaNerdFontCompleteMono Nerd Font"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
# startup_mode = "Maximized"

[window.padding]
x = 8
y = 8
