#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8


#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

#
# java
#
[[ -e "/usr/libexec/java_home" ]] && export JAVA_HOME="$(/usr/libexec/java_home)"

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /usr/local/opt/llvm/bin
  $HOME/.cargo/bin
  $HOME/.yarn/bin
  $HOME/.config/yarn/global/node_modules/.bin
  $HOME/.fastlane/bin
  $HOME/.iterm2
  $path
)


# Delay transition between modes (n * 0.1 sec.)
export KEYTIMEOUT=1


#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-X -F -g -i -M -R -S -w -z-4 -x4'


# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi


# Fix git auto-complete to search only local files
__git_files () { 
    _wanted files expl 'local files' _files  
}


#
# setopt
#
# disable warn glob with no match
setopt nonomatch

# turn on spelling correction
# setopt correct

# don't save duplicates in command history
setopt histignoredups
# don't allow accidental file over-writes
# setopt noclobber

# change directory with no cd
setopt autocd

# do not exit on end-of-file
setopt ignore_eof

export GTAGSLABEL=pygments

#
# powerlevel10k
#
export POWERLEVEL9K_PROMPT_ON_NEWLINE=true


#
# zsh-iterm-touchbar
#
export TOUCHBAR_GIT_ENABLED=true
export YARN_ENABLED=true
