#
# Z-Prezto.
#
if ! [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
  git clone --recursive-submodules https://github.com/belak/prezto-contrib "${ZDOTDIR:-$HOME}/.zprezto/contrib"
fi

source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

#
# FASD
#
if command -v fasd &> /dev/null ; then
  eval "$(fasd --init auto)"

  alias v="fasd -f -e ${EDITOR}"     # quick opening files with vim
  if [[ "$OSTYPE" == darwin* ]]; then
    alias m="fasd -f -e mplayer" # quick opening files with mplayer
    alias o="fasd -f -e open"    # quick opening files with open
  fi
fi

#
# Alias
#
alias vim='nvim'
alias vims='nvim -S Session.vim'
alias emacs='emacs -nw'
alias tmr=tmuxinator

alias hidden-show='defaults write com.apple.finder AppleShowAllFiles -bool YES && killall Finder'
alias hidden-hide='defaults write com.apple.finder AppleShowAllFiles -bool NO && killall Finder'

alias gts='git tag --sort=objecttype --sort=-creatordate | git show --date=local --pretty="format:%C(auto)%h%C(green)%d %C(blue)%an %C(auto)%s %x1b[2m%ad%x1b[0m%Creset" -s --stdin'
alias giw='git diff -U0 -w --no-color "$@" | git apply --cached --ignore-whitespace --unidiff-zero -'
alias glp='git log -p'

alias note="vim -S ~/Dropbox/.note/Session.vim"
alias c="clear"


# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
test -e "${HOME}/.zshrc.local" && source "${HOME}/.zshrc.local"

