#
# Z-Prezto.
#
if ! [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
  git clone --recursive https://github.com/jadeCNX/prezto-contrib "${ZDOTDIR:-$HOME}/.zprezto/contrib"
fi

source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"


#
# FASD
#
if command -v fasd &> /dev/null ; then
  eval "$(fasd --init auto)"

  alias v="fasd -f -e ${EDITOR}"     # quick opening files with vim
  alias t="fasd -f -e \"less +F\""     # quick opening files with vim
  
  if [[ "$OSTYPE" == darwin* ]]; then
    # alias m="fasd -f -e mplayer" # quick opening files with mplayer
    alias o="fasd -f -e open"    # quick opening files with open
  fi
fi


#
# FZF
#
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# Use ;; as the trigger sequence instead of the default **
export FZF_COMPLETION_TRIGGER=';;'

# Options to fzf command
export FZF_COMPLETION_OPTS='+c -x'

export CHEAT_USE_FZF=true

if [ -n "$TMUX" ]; then
  export FZF_TMUX=1
fi
# Use fd (https://github.com/sharkdp/fd) instead of the default find
# command for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}
# export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob="!.git/*" --glob="!node_modules/*"'
# export FZF_DEFAULT_COMMAND='fd --type file --follow -E .git -E node_modules'


#
# Alias
#
alias vi='/usr/local/vim'
alias vim='nvim'
alias vims='nvim -S Session.vim'
alias emacs='emacs -nw'
alias tmr=tmuxinator

alias hidden-show='defaults write com.apple.finder AppleShowAllFiles -bool YES && killall Finder'
alias hidden-hide='defaults write com.apple.finder AppleShowAllFiles -bool NO && killall Finder'

alias dkct='docker-compose logs -f --tail 10'

alias note='vim -S ~/Dropbox/.notes/Session.vim'
alias c='clear'

alias vtop='vtop --theme wizard'

alias m='{ pgrep -vx tmux > /dev/null && tmux new -d -s delete-me && tmux run-shell ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh && tmux kill-session -t delete-me && tmux attach } || tmux attach'

# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
test -e "${HOME}/.zshrc.local" && source "${HOME}/.zshrc.local"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
