#!/usr/bin/env bash

GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)

if [[ "$GIT_REMOTE" =~ "github" ]] || [[ "$GIT_REMOTE" =~ "gh1" ]] || [[ "$GIT_REMOTE" =~ "gh2" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]] || [[ "$GIT_REMOTE" =~ git.alm.set ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
