return {
  { "AndrewRadev/linediff.vim" },
  { "AndrewRadev/switch.vim" },
  { "chrisbra/csv.vim", ft = { "csv", "tsv" } },
  { "dag/vim-fish", ft = { "fish" } },
  { "dashboard-nvim", enabled = false },
  { "dhruvasagar/vim-zoom" },
  { "eandrju/cellular-automaton.nvim" },
  { "editorconfig/editorconfig-vim" },
  { "ellisonleao/glow.nvim", ft = { "markdown" } },
  { "felipec/vim-sanegx", event = "BufRead" },
  { "folke/flash.nvim", enabled = false },
  { "glts/vim-textobj-comment", dependencies = "kana/vim-textobj-user" },
  { "junegunn/vim-easy-align" },
  { "kana/vim-textobj-indent", dependencies = "kana/vim-textobj-user" },
  { "kana/vim-textobj-user" },
  { "nacro90/numb.nvim", event = "BufRead", opts = { show_numbers = true, show_cursorline = true } },
  { "olimorris/onedarkpro.nvim" },
  { "ThePrimeagen/vim-be-good", enabled = false },
  { "tommcdo/vim-exchange" },
  { "tpope/vim-abolish" },
  { "tpope/vim-repeat" },
  { "tpope/vim-rsi" },
  { "Vigemus/iron.nvim", lazy = true },
  { "vimtaku/vim-textobj-keyvalue", dependencies = "kana/vim-textobj-user" },
}
