return {
  { "AndrewRadev/linediff.vim" },
  { "AndrewRadev/switch.vim" },
  { "chrisbra/csv.vim", ft = { "csv", "tsv" } },
  { "dag/vim-fish", ft = { "fish" } },
  { "dashboard-nvim", enabled = false },
  { "dhruvasagar/vim-zoom" },
  { "eandrju/cellular-automaton.nvim" },
  { "editorconfig/editorconfig-vim" },
  { "ellisonleao/glow.nvim", ft = { "markdown" } },
  { "folke/flash.nvim", enabled = false },
  { "junegunn/vim-easy-align" },
  { "nacro90/numb.nvim", event = "BufRead", opts = { show_numbers = true, show_cursorline = true } },
  { "olimorris/onedarkpro.nvim" },
  { "ThePrimeagen/vim-be-good", enabled = false },
  { "tommcdo/vim-exchange" },
  { "tpope/vim-abolish" },
  { "tpope/vim-fugitive" },
  { "Vigemus/iron.nvim", lazy = true },
}
